#!/bin/bash
export CAP_MATRIX=1
echo "the env CAP_MATRIX is set: calculate the cap matrix no matter what voltages are configured."

./cap3d

extracted_string=$(grep -o '/[^/]*\.elx' cap3d.log | sed 's,^/,,; s/\.elx$//')
new_logfile_name="$extracted_string.log"
if [ ! -d "result" ]; then
    mkdir "result"
fi
mv cap3d.log "result/$new_logfile_name"
echo "Logfile has been saved to: result/$new_logfile_name"
